/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WarenkorbRouteImport } from './routes/warenkorb'
import { Route as ProduktSlugRouteImport } from './routes/produkt.$slug'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WarenkorbRoute = WarenkorbRouteImport.update({
  id: '/warenkorb',
  path: '/warenkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktSlugRoute = ProduktSlugRouteImport.update({
  id: '/produkt/$slug',
  path: '/produkt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/warenkorb': typeof WarenkorbRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/warenkorb': typeof WarenkorbRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/warenkorb': typeof WarenkorbRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/warenkorb'
    | '/produkt/$slug'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop'
    | '/warenkorb'
    | '/produkt/$slug'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/shop'
    | '/warenkorb'
    | '/produkt/$slug'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRoute
  WarenkorbRoute: typeof WarenkorbRoute
  ProduktSlugRoute: typeof ProduktSlugRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warenkorb': {
      id: '/warenkorb'
      path: '/warenkorb'
      fullPath: '/warenkorb'
      preLoaderRoute: typeof WarenkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$slug': {
      id: '/produkt/$slug'
      path: '/produkt/$slug'
      fullPath: '/produkt/$slug'
      preLoaderRoute: typeof ProduktSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRoute,
  WarenkorbRoute: WarenkorbRoute,
  ProduktSlugRoute: ProduktSlugRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
